[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.30.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/netlify-cms-academic"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/wowchemy"
